export * from './root'
export * from './MainPage/MainPage'
// export * from './CatalogPage/CatalogPage'
// export { ProductsPage as default } from './ProductsPage/ProductsPage'
export * from './SingleProductPage/SingleProductPage'
// export * from './CartPage/CartPage'
export * from './ContactsPage/ContactsPage'
export { DeliveryPage as default } from './DeliveryPage/DeliveryPage'
export * from './PersonalArea/PersonalArea'
// export * from './SearchPage/SearchPage'