export * from './root'
export * from './MainPage/MainPage'
export * from './SingleProductPage/SingleProductPage'
export * from './ContactsPage/ContactsPage'
export * from './PersonalArea/PersonalArea'