export * from './root'
export * from './MainPage/MainPage'
export * from './CatalogPage/CatalogPage'
export * from './ProductsPage/ProductsPage'
export * from './SingleProductPage/SingleProductPage'
export * from './CartPage/CartPage'
export * from './ContactsPage/ContactsPage'
export * from './DeliveryPage/DeliveryPage'